### ISSUE TITLE
example error.

### ISSUE THREAD

**Issue by leoGalani** [koa-modules/i18n#1]
the exemple is missing a caracter.. !

app.use(i18n(app, {
...

no

app.use(18n(app, {

**Comment by niksajanjic** [comment]
Hi, I don't want to open a separate issue, but it seems like there are still some issues with the examples. For instance, in this example https://github.com/koa-modules/i18n/blob/master/examples/no-tempalte.js, there is an invalid option when configuring i18n module:

```
  query: true                     //  optional detect querystring - `/?lang=en-US`
```

There are 2 issues with it:
1) `query: true` doesn't seem do anything for me, it simply doesn't work, what I had to do is to put `modes: ['query']` for it to work. I haven't tried that specific example, but in my code `query` option doesn't work so I have to use `modes` option.
2) This issue is more of a confusing one. The comment next to `query` option says that you can use optional `/?lang=en-US` queystring detect. What is confusing is the fact that `koa-locale` default value is `locale` not `lang`. If we want to change the default one, we need to pass the string while instantiating locale, like this:
```
// Required! 
locale(app, 'lang');
```
So, either comment needs to be changed or this line of code needs to be updated to make it work. Right now, `/?lang=en` won't do anything, it will still serve page in Chinese.

Until these issues are fixed, it will always serve the page in Chinese.
